version: "3.8"
services:
  # app:
  #   build: ./frontend/xalFront/
  #   command: sh -c "ng serve"
  #   ports:
  #     - 4200:4200
  #   working_dir: /home/node/app
  #   volumes:
  #     - ./:/home/node/app
  #     - node_modules:/home/node/app/node_modules
  #   links:
  #     - api
  api:  
    container_name: 'Api'
    build: ./wraperAPI/
    ports:
      - '8000:8000'
    expose:
      - '8000'
    links:
      - mysql

  mysql:
    container_name: 'db'
    tty: true
    build: ./mysql/
    ports:
      - '3306:3306'
    expose:
      - '3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
volumes:
  node_modules:
    
 
 
